receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: 0.0.0.0:4318

processors:
  attributes/kong_trace_context:
    actions:
      - key: demo.observability.source
        value: kong
        action: upsert
      - key: demo.observability.pipeline
        value: kong->otel-collector->jaeger
        action: upsert
      - key: demo.trace_backend
        value: jaeger
        action: upsert
  batch:

exporters:
  otlphttp/jaeger:
    endpoint: http://jaeger:4318
  prometheus:
    endpoint: 0.0.0.0:9464
  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - attributes/kong_trace_context
        - batch
      exporters:
        - otlphttp/jaeger
        - debug
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - prometheus
        - debug
